version: '3.8'

services:
  my-service:
    image: xxxx  # 使用你的镜像
    container_name: my_service      # 容器名称
    working_dir: /app_cp
    ports:
      - "xxxx:xxxx"
    volumes:
      - ./local-app:/app_cp            # 将本地的 ./local-app 目录挂载到容器中的 /app_cp 目录
    stdin_open: true                # 启用交互式输入
    tty: true                       # 分配伪终端
    entrypoint: ["sh"]
    command: 
        -c "read read;"              # 启动 shell
